pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/jayaprakashn24/Jenkins_beginner-to-advance.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('Day - 11') {
                    sh 'pip3 install -r requirements.txt'
                }
            }
        }

        stage('Run Application') {
            steps {
                dir('Day - 11') {
                    sh 'python3 app.py'
                }
            }
        }
    }

    post {
        success {
            echo 'Dependencies installed and app executed successfully ✅'
        }
    }
}