pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/jayaprakashn24/Jenkins_beginner-to-advance.git'
            }
        }
        stage('Run Python') {
            steps {
                dir('Day - 9') {
                    sh 'python3 app.py'
                }
            }
        }
    }
}